### ISSUE TITLE
Windows 7 installation problem

### ISSUE THREAD

**Issue by jeffrey-l-turner** [openfin/fin-trader#9]
I tried to install the Hyperblotter using the Readme instructions and the `gulp build` failed with an error on the gulp-autoprefixer module. I am using node 4.4.7 and I received the following error:

 events.js:141
      throw er; // Unhandled 'error' event
      ^
 Error: Unsupported source map encoding charset=utf8;base64

I updated the package.json file to change the gulp-autoprefixer to "^3.1.1" and this resolved the issue. I will also submit a PR.

**Comment by dcchuck** [comment]
Thanks for the PR! Merged in, this was actually an issue for me on Mac OS as well.
